shared-version = true
consolidate-commits = true
pre-release-commit-message = "Release v{{version}}"
tag-prefix = ""
tag-name = "v{{version}}"
tag-message = "v{{version}}"
push = false
publish = false
