[package]
name = "nidx-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nidx = { path = "../.." }
js-sys = "0.3"
wasm-bindgen = "0.2.112"

[dev-dependencies]
wasm-bindgen-test = "0.3"
